//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCards.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCard
    {
        public int JobCardID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid DesignerID { get; set; }
        public System.DateTime JobDate { get; set; }
        public string QuoteRef { get; set; }
        public Nullable<System.Guid> JobTypeID { get; set; }
        public Nullable<System.Guid> MaterialID { get; set; }
        public bool IsDeleted { get; set; }
        public int TaskStep { get; set; }
        public Nullable<int> CreatedID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UVPrinterID { get; set; }
        public Nullable<System.DateTime> UVPrintedDate { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> CladingID { get; set; }
        public Nullable<System.DateTime> CladingDate { get; set; }
        public Nullable<int> InstallID { get; set; }
        public Nullable<System.DateTime> InstalDate { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Designer Designer { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Material Material { get; set; }
    }
}
