//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCards.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUserProfile
    {
        public int SYSUserProfileID { get; set; }
        public int SYSUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int CreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual SYSUser SYSUser { get; set; }
    }
}
