//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCards.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUserRole
    {
        public int SYSUserRoleID { get; set; }
        public int SYSUserID { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
